# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_products', '0002_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='online_shop_products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop_products.Product')),
            ],
        ),
    ]
