# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_products', '0004_auto_20170802_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
