# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sensor', models.CharField(max_length=264)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
