# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_orders', '0002_auto_20170907_0225'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercheckout',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usercheckout',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
