# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_carts', '0007_cart_tax_percentage'),
        ('online_shop_orders', '0004_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_total_price', models.DecimalField(decimal_places=2, default=6.66, max_digits=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='online_shop_orders.UserAddress')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop_carts.Cart')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='online_shop_orders.UserAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop_orders.UserCheckout')),
            ],
        ),
    ]
