# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated',
        ),
    ]
