# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_carts', '0003_auto_20170809_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
